### ISSUE TITLE
Hey, quick question :) 

### ISSUE THREAD

**Issue by BudMuecke** [Worvast/adventofcode2022#1]
Hey @Worvast , sorry that I misuse github issues for my question, but I did not find any other way to message you.
If you had a discord account named Worvast, then you might be the right person.

I randomly came across your conversation with Shiqan back in 2020 in a fortnite research group discord server. You were talking about parsing Squad replays. Did you manage to do it? I want to do the same and I wonder how to do it correctly. 

If you are not the right person, sorry to disturb you. Have a great day! 

PS: I visited Tenerife and the canaries in general quite often and I must admit: Beautiful Islands!

**Comment by Worvast** [comment]
Hi @BudMuecke, i cant manage to id finally and i loose the focus and leave it. I dont remember too much, except, you can use the core of the Fornite parser to extract some information of the Squad replays but the data are not in the same order/search of Fornite parser soo need modifications and some investigation, too much work soo that why i leave it because only want it a little not too much hahahaha

Good luck!
